In [1]:
import numpy as np

In [2]:
#Basic Array Creation

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = np.array([1,2,3.4])
a

array([1. , 2. , 3.4])

In [11]:
l = [[1,2,3], [4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Array Generation Function

In [15]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr2 = np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr3 = np.ones((2,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr4 = np.linspace(1,2,10)  #Linear-Space
arr4

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
# Random Generation Function

In [23]:
arr5 = np.random.rand(5)   # this is using random lib also 
arr5

array([0.26667427, 0.04660011, 0.68143166, 0.30893068, 0.55198405])

In [24]:
arr6 = np.random.randn(10)
arr6

array([ 0.88631875, -0.44417866,  1.31288611, -1.42433814, -1.56386974,
       -1.03688581,  1.40961394,  1.02193732,  2.57463083,  0.21067843])

In [25]:
arr7 = np.random.randint(10,20)    #giving random num b/w 10 to 20
arr7

13

In [ ]:
#Array Attributes

In [28]:
arr8 = np.array([[4,5,6],[7,8,9],[1,2,3]])
arr8

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [31]:
arr8.size

9

In [32]:
arr8.shape

(3, 3)

In [33]:
arr.dtype

dtype('int64')

In [ ]:
#Array Methods

In [34]:
arr8

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [35]:
arr8.min()

np.int64(1)

In [37]:
arr8.max()

np.int64(9)

In [39]:
arr8.sum()

np.int64(45)

In [40]:
np.sum(arr8,axis = 0)    # Total Sum Column-wise

array([12, 15, 18])

In [41]:
np.sum(arr8,axis = 1)    # Total Sum Row-wise

array([15, 24,  6])

In [42]:
arr8.mean()

np.float64(5.0)

In [43]:
arr8.std()

np.float64(2.581988897471611)

In [44]:
arr8.argmax()   # max element indexing no

np.int64(5)

In [46]:
arr8.argmin()  #min element index no

np.int64(6)

In [ ]:
# Reshaping and re-sizing

In [47]:
arr9 = np.arange(1,31)
arr9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
arr10 = arr9.reshape(6,5)  #u have to reshape acc to the element count , we did this coz we want the arr in 2-d or 3-d form
arr10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# Numpy indexing and slicing vectors

In [51]:
arr11 = np.arange(10,21)
arr11

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
arr11[7] # I am calling index 7th this is called indexing

np.int64(17)

In [54]:
arr11[1:6] # I want element from 11 to 15 this is called slicing

array([11, 12, 13, 14, 15])

In [55]:
#Numpy slicing and indexing of matrix

In [57]:
arr12 = np.arange(1,31).reshape(6,5)
arr12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [61]:
arr12[0,0] #first element of the first row and first col

np.int64(1)

In [65]:
slice = arr12[3:,3:]   
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [67]:
row = arr12[:,2]
row

array([ 3,  8, 13, 18, 23, 28])

In [68]:
#Boolean Indexing

In [69]:
arr13 = np.arange(11,21)
arr13

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
bool_index = arr13 % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [74]:
arr13 = arr13[bool_index]
arr13

array([12, 14, 16, 18, 20])

In [75]:
# ARRAY OPERATIONS

In [76]:
#Arthimtic oper

In [77]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [79]:
a1 + a2

array([-5, -5, -5, -5, -5])

In [80]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [81]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [82]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [83]:
a1 // a2

array([0, 0, 0, 0, 0])

In [84]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [85]:
#Broad-Casting

In [87]:
l = [10,20,30,40,50]

arr14 = np.array(l)

arr14 + 10   #every element of arr added with 10 this is called bre]oad casting

array([20, 30, 40, 50, 60])

In [88]:
arr15 = np.arange(1,31).reshape(6,5)
arr15

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [89]:
arr15 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [90]:
#Deep and Shallow Copy

In [91]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [94]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
a 
b = a.copy()

In [96]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [98]:
#Matrix oper

In [99]:
A = np.array([[1,2],[3,4]])  # in stack we cannot use matrix we have to use vectors
B = np.array([[5,6],[7,8]])

In [100]:
A

array([[1, 2],
       [3, 4]])

In [101]:
B

array([[5, 6],
       [7, 8]])

In [102]:
A @ B  # at the rate is use for matrix multiplication

array([[19, 22],
       [43, 50]])

In [103]:
np.dot(A,B)   # another method for matrix mult

array([[19, 22],
       [43, 50]])

In [104]:
A.T   # T is use for transpose means rows becomes column

array([[1, 3],
       [2, 4]])

In [105]:
# Advance array manipulation

In [106]:
# 1.Stacking array

In [107]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [108]:
np.vstack((a,b))   # vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
np.hstack((a,b))   # horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [111]:
# 2.Splitting array

In [113]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
np.hsplit(c,2)  #horizontally split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [122]:
d = np.vsplit(c,4)

In [123]:
for i in d :
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
