In [1]:
import numpy as np

#columns :[Age,Math marks, science marks]
data = np.array([
    [18,85,78],   #student 1
    [19,92,98],   #student 2
    [17,76,95],   #student 3
    [18,65,70],   #student 4
    [20,90,85]    #student 5
    
])

In [2]:
# Get the shape of the matrix

data.shape

(5, 3)

In [3]:
#find the avg age of students
np.mean(data[:,0])

np.float64(18.4)

In [4]:
#extract math marks of all student
data[:,1]

array([85, 92, 76, 65, 90])

In [5]:
#find the highest science marks

np.max(data[:,2])

np.int64(98)

In [6]:
#get detail of student who get more than 90 marks in math

data[data[:,1] > 90]

array([[19, 92, 98]])

In [7]:
#increase math marks of all student by 5

a = data[:,1]

a + 5

array([90, 97, 81, 70, 95])

In [8]:
#find how many students are younger than 19
len(data[data[:,0] < 19])

3

In [9]:
#cal avg marks of in each subject(col - wise)
a = np.mean(data[:,1:],axis = 0)
a

array([81.6, 85.2])

In [10]:
#get data of students atleast who get 80 in both sub
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 98],
       [20, 90, 85]])

In [11]:
#replace all science marks < 70 with 0
data[:,2][data[:,2]<=75] = 0
data

array([[18, 85, 78],
       [19, 92, 98],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

In [19]:
#for suduko code

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [20]:
a = np.sum(s,axis=1)
for i in a:
    if i != 45:
        print("Not a suduko")
        break
else:
    print("Suduko")

Suduko
